"""
test_evaluator.py - Smoke test for check_groundedness() with 3 example pairs.

Usage:
    python test_evaluator.py

What this measures
------------------
check_groundedness() uses Moss semantic similarity to detect TOPICAL
groundedness: is the response discussing content drawn from the context,
or is it talking about something else entirely?

  High score  -- response is on-topic with the context (likely grounded)
  Low score   -- response is off-topic (likely hallucinating a different domain)

This catches the most common RAG failure mode (LLM ignores retrieved context
and answers from training data about a different subject), but it does NOT
detect within-topic factual contradictions -- that requires an NLI model.

Threshold: GROUNDEDNESS_THRESHOLD = 0.6 (see evaluator.py to change it)
"""

import asyncio

from evaluator import EvalResult, check_groundedness, setup_eval_index

# ---------------------------------------------------------------------------
# Shared context
# ---------------------------------------------------------------------------

CONTEXT = (
    "Solar power is generated by converting sunlight into electricity using "
    "photovoltaic (PV) cells. Modern solar panels are typically made from "
    "silicon wafers and achieve efficiencies of 20-25% in commercial "
    "applications. Panel costs have fallen over 90% in the last decade, "
    "making solar one of the cheapest sources of new electricity generation."
)

# ---------------------------------------------------------------------------
# Test cases
# ---------------------------------------------------------------------------

TEST_CASES = [
    {
        "label"   : "Grounded -- paraphrases key facts from the context",
        "response": (
            "Solar panels convert sunlight to electricity via photovoltaic cells "
            "made from silicon. Commercial panels typically reach 20-25% "
            "efficiency, and costs have dropped dramatically over the past decade."
        ),
        "expected": "grounded",
        "why"     : "Direct paraphrase of context facts -- high topical overlap expected.",
    },
    {
        "label"   : "Ungrounded -- completely different topic (no overlap with context)",
        "response": (
            "The Federal Reserve raised interest rates by 0.25 percentage points "
            "to combat inflation. Bond yields rose sharply as investors repriced "
            "credit risk across fixed-income markets."
        ),
        "expected": "ungrounded",
        "why"     : "Monetary policy / finance -- nothing in common with solar panels.",
    },
    {
        "label"   : "Borderline -- same broad domain, but specifics not in context",
        "response": (
            "Renewable energy sources such as wind and hydropower have become "
            "increasingly cost-competitive with natural gas in many regions."
        ),
        "expected": "borderline",
        "why"     : (
            "Renewable energy is adjacent to solar, but this response discusses "
            "wind/hydro and gas -- none of which appear in the context. "
            "Score should land around the threshold."
        ),
    },
]

# ---------------------------------------------------------------------------
# Printer
# ---------------------------------------------------------------------------

def _print_result(tc: dict, result: EvalResult) -> None:
    expected = tc["expected"]
    if expected == "borderline":
        match_tag = "[NOTE] borderline -- could go either way"
    elif result.verdict == expected:
        match_tag = "[PASS]"
    else:
        match_tag = f"[NOTE] expected '{expected}', got '{result.verdict}'"

    print(f"  Label    : {tc['label']}")
    print(f"  Why      : {tc['why']}")
    print(f"  Score    : {result.groundedness_score:.4f}")
    print(f"  Verdict  : {result.verdict.upper()}")
    print(f"  Expected : {expected}  {match_tag}")
    print(f"  Latency  : {result.latency_ms:.0f} ms")
    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def main() -> None:
    print("=" * 64)
    print("  Groundedness Evaluator - check_groundedness() smoke test")
    print("=" * 64)
    print()
    print("  Context: solar photovoltaic technology (3 sentences)")
    print()

    try:
        await setup_eval_index()
    except EnvironmentError as exc:
        print(f"[ERROR] {exc}")
        return

    print("-" * 64)
    print()

    for i, tc in enumerate(TEST_CASES, start=1):
        print(f"[{i}/{len(TEST_CASES)}]")
        result = await check_groundedness(tc["response"], CONTEXT)
        _print_result(tc, result)

    print("-" * 64)
    print("Note: scores measure topical similarity, not factual accuracy.")
    print("      For contradiction detection, an NLI model is needed.")
    print("Done.")


if __name__ == "__main__":
    asyncio.run(main())
